version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 20


  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install


  build:
    commands:
      - echo "Building Frontend application"
      - echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env
      - npm run build


  post_build:
    commands:
      - echo "Deploying to S3 bucket ${S3_BUCKET_NAME}"
      - aws s3 sync build s3://${S3_BUCKET_NAME} --delete
      - echo "Invalidating CloudFront distribution ${CLOUDFRONT_DISTRIBUTION_ID}"
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      - echo "🎉 Frontend deployed successfully to S3 + CloudFront!"
