name: Backend Deployment
on:
  push:
    branches:
        - team2-lumanti


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Run Backend Deployment Script
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        GITHUB_SHA: ${{ github.sha }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      run: |
        chmod +x ./scripts/deploy-backend.sh
        ./scripts/deploy-backend.sh
